# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [46]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [50]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [52]:
# verificando as colunas da base de dados
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [57]:
# filtrando apneas as colunas que iremos utilizar em uma nova variável
sinasc_1 = sinasc_raw[['munResNome', 'IDADEMAE', 'IDADEPAI']]

In [59]:
# Verificando a quantidade de linhas vazias na coluna de idade do pai
sinasc_1['IDADEPAI'].isna().sum()

19421

In [61]:
# Verificando a média de idade dos pais para cada municipio
sinasc_1.groupby('munResNome').mean()

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

In [63]:
# Agora removendo as linhas vazias
sinasc_1.dropna().groupby('munResNome').mean()

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.892857  29.548701
Alto Alegre dos Parecis    24.679104  29.179104
Alto Paraíso               22.833333  28.833333
Alvorada D'Oeste           26.825243  30.757282
Ariquemes                  28.133333  32.466667
Buritis                    24.750000  30.812500
Cabixi                     32.166667  34.333333
Cacaulândia                31.000000  36.333333
Cacoal                     26.978605  30.931854
Campo Novo de Rondônia     24.900000  30.500000
Candeias do Jamari         23.684211  29.894737
Castanheiras               28.071429  30.392857
Cerejeiras                 28.361111  31.652778
Chupinguaia                26.888889  29.629630
Colorado do Oeste          31.161290  34.354839
Corumbiara                 29.000000  32.470588
Costa Marques              25.250000  30.613636
Cujubim                    27.400000  31.400000
Espigão D'Oeste            26.808176  31.198113
Governador Jorge Teixeira  25.555556  29.222222
Guajará-Mirim              26.058824  30.470588
Itapuã do Oeste            31.375000  42.500000
Jaru                       28.450704  32.197183
Ji-Paraná                  27.282819  31.132239
Machadinho D'Oeste         26.048077  31.326923
Ministro Andreazza         27.890411  33.849315
Mirante da Serra           26.928571  32.154762
Monte Negro                27.642857  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   27.104167  30.520833
Nova Mamoré                26.051282  31.692308
Nova União                 27.371429  31.371429
Novo Horizonte do Oeste    26.988235  31.588235
Ouro Preto do Oeste        27.109920  31.233244
Parecis                    26.973684  32.473684
Pimenta Bueno              25.449807  29.745174
Pimenteiras do Oeste       32.600000  35.600000
Porto Velho                28.355655  32.352679
Presidente Médici          26.170854  30.150754
Primavera de Rondônia      28.083333  31.888889
Rio Crespo                 26.000000  28.000000
Rolim de Moura             26.549701  30.360479
Santa Luzia D'Oeste        26.043956  30.703297
Seringueiras               25.058824  30.500000
São Felipe D'Oeste         26.979167  31.395833
São Francisco do Guaporé   26.944444  31.638889
São Miguel do Guaporé      27.469136  32.666667
Teixeirópolis              27.454545  31.500000
Theobroma                  24.916667  30.083333
Urupá                      27.116071  31.008929
Vale do Anari              27.133333  34.000000
Vale do Paraíso            25.604651  29.976744
Vilhena                    30.611765  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [66]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [68]:
# Filtrando os registros para o dia 2019-10-24
sinasc_raw_filtrado = sinasc_raw[sinasc_raw['DTNASC'] == '2019-10-24']

In [70]:
# Calculando o peso médio por sexo e escolaridade da mãe e usando o reset index para obter a visualização do dataframe
sinasc_raw_filtrado.groupby(['SEXO', 'ESCMAE'])['PESO'].mean().reset_index()

        SEXO           ESCMAE         PESO
0   Feminino  12 anos ou mais  3055.000000
1   Feminino       4 a 7 anos  2500.000000
2   Feminino      8 a 11 anos  3027.777778
3  Masculino       1 a 3 anos  3310.000000
4  Masculino  12 anos ou mais  3501.428571
5  Masculino       4 a 7 anos  3714.285714
6  Masculino      8 a 11 anos  3464.600000

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [73]:
# Agrupando os nascimentos por nome do municipio e verificando qual é o municipio com menos nascimentos
sinasc_raw.groupby('munResNome')['DTNASC'].count().sort_values().head(5)

munResNome
Município ignorado - RO     1
Castanheiras               32
Pimenteiras do Oeste       40
Primavera de Rondônia      43
Parecis                    44
Name: DTNASC, dtype: int64

In [98]:
# Convertendo DTNASC para datetime e extraindo o ano
sinasc_raw['DTNASC'] = pd.to_datetime(sinasc_raw['DTNASC'])
sinasc_raw['ANO_NASC'] = sinasc_raw['DTNASC'].dt.year

# Filtrando para o ano de 2019
sinasc_2019 = sinasc_raw[sinasc_raw['ANO_NASC'] == 2019]

# Agrupando por município e contando os nascimentos
nascimentos_por_municipio = sinasc_2019.groupby('munResNome')['DTNASC'].count().sort_values()

# Encontrando o município com menos nascimentos
municipio_menos_nascimentos = nascimentos_por_municipio.index[0]

# Filtrando e agregando dados para o município com menos nascimentos
sinasc_menor_municipio = sinasc_2019[sinasc_2019['munResNome'] == municipio_menos_nascimentos]
estatisticas_idades = sinasc_menor_municipio.groupby('munResNome')[['IDADEMAE', 'IDADEPAI']].agg(['mean', 'max', 'min'])

print(f"O município com menos nascimentos em 2019 é: {municipio_menos_nascimentos}")
print(estatisticas_idades)

O município com menos nascimentos em 2019 é: Município ignorado - RO
                        IDADEMAE         IDADEPAI
                            mean max min     mean   max   min
munResNome
Município ignorado - RO     24.0  24  24     22.0  22.0  22.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

In [6]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [7]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [4]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [100]:
# Alterando o formato da coluna para data
sinasc_raw['DTNASC'] = pd.to_datetime(sinasc_raw['DTNASC'])

In [102]:
# Filtrar os registros que estão no mês de março
nascimentos_marco = sinasc_raw[sinasc_raw['DTNASC'].dt.month == 3]
nascimentos_marco.head(2)

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea,ANO_NASC
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273,2019
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025,2019

In [104]:
# Contando o número de nascimentos em março
nascimentos_marco.shape[0]

2456

In [106]:
# Descobrindo qual foi o municipio com maior quantiadde de nascimentos no mes de março
nascimentos_marco['munResNome'].value_counts().idxmax()

'Porto Velho'

In [108]:
# O valor de nascimentos desse municipio
nascimentos_marco['munResNome'].value_counts().max()

744

In [110]:
# Agrupando os dados por nascimento em porto velho e no mes de março
porto_velho = nascimentos_marco[nascimentos_marco['munResNome'] == 'Porto Velho'].groupby('munResNome')

In [116]:
def analisar_municipio(df, municipio):
    """
    Analisa os dados de nascimentos para um município específico.

    Args:
        df (pd.DataFrame): DataFrame com os dados de nascimentos.
        municipio (str): Nome do município a ser analisado.

    Returns:
        pd.DataFrame: DataFrame com as estatísticas calculadas.
    """

    # Filtra os registros do município informado
    municipio_df = df[df['munResNome'] == municipio]

    # Verifica se o município existe nos dados
    if municipio_df.empty:
        print(f"Município '{municipio}' não encontrado nos dados.")
        return None

    # Agrupa os dados e calcula as estatísticas
    resultados = municipio_df.groupby('munResNome').agg({
        'QTDFILVIVO': ['min', 'mean', 'max'],
        'QTDFILMORT': ['min', 'mean', 'max'],
        'IDADEMAE': ['min', 'mean', 'max'],
        'IDADEPAI': ['min', 'mean', 'max']
    })

    return resultados

            QTDFILVIVO                QTDFILMORT                IDADEMAE  \
                   min      mean  max        min      mean  max      min
munResNome
Porto Velho        0.0  1.295056  9.0        0.0  0.352734  4.0       14

                           IDADEPAI
                  mean max      min       mean   max
munResNome
Porto Velho  26.596774  44     19.0  34.629032  62.0